# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawing',
            old_name='location_x',
            new_name='x1',
        ),
        migrations.RenameField(
            model_name='drawing',
            old_name='location_y',
            new_name='x2',
        ),
        migrations.AddField(
            model_name='drawing',
            name='y1',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drawing',
            name='y2',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
